/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Activity: typeof import('./src/components/profile/Activity.vue')['default']
    AddTodo: typeof import('./src/components/AddTodo.vue')['default']
    BaseCheckbox: typeof import('./src/components/customInput/BaseCheckbox.vue')['default']
    BaseInput: typeof import('./src/components/customInput/BaseInput.vue')['default']
    BaseInputArea: typeof import('./src/components/customInput/BaseInputArea.vue')['default']
    BaseRadio: typeof import('./src/components/customInput/BaseRadio.vue')['default']
    BaseRadioGroup: typeof import('./src/components/customInput/BaseRadioGroup.vue')['default']
    BaseSelect: typeof import('./src/components/customInput/BaseSelect.vue')['default']
    ChangePassword: typeof import('./src/components/auth/ChangePassword.vue')['default']
    Detail: typeof import('./src/components/Detail.vue')['default']
    Edit: typeof import('./src/components/Edit.vue')['default']
    Forgot: typeof import('./src/components/auth/Forgot.vue')['default']
    Profile: typeof import('./src/components/profile/Profile.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    SignIn: typeof import('./src/components/auth/SignIn.vue')['default']
    Todos: typeof import('./src/components/Todos.vue')['default']
    Topbar: typeof import('./src/components/layout/Topbar.vue')['default']
  }
}
